import { ICard, CardType, CardRow, CardAbilities, IGameState, Fraction, GameMode } from "./types";

export const cards: { [name: string]: ICard } = {
  Ballista: {
    name: "Ballista",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Siege,
    strength: 6,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Dethmold: {
    name: "Dethmold",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Range,
    strength: 6,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Dun_Banner_Medic: {
    name: "Dun_Banner_Medic",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Siege,
    strength: 5,
    ability: CardAbilities.Medic,
    comment: "Part of a base deck",
  },
  Kaedweni_Siege_Expert: {
    name: "Kaedweni_Siege_Expert",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Siege,
    strength: 1,
    ability: CardAbilities.Moral_Boost,
    comment: "Part of a base deck",
  },
  Keira_Metz: {
    name: "Keira_Metz",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Range,
    strength: 5,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Prince_Stennis: {
    name: "Prince_Stennis",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Melee,
    strength: 5,
    ability: CardAbilities.Spy,
    comment: "Part of a base deck",
  },
  Redanian_Foot_Soldier: {
    name: "Redanian_Foot_Soldier",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Melee,
    strength: 1,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Sabrina_Glevissig: {
    name: "Sabrina_Glevissig",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Range,
    strength: 4,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Sheldon_Skaggs: {
    name: "Sheldon_Skaggs",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Range,
    strength: 4,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Siegfried_of_Denesle: {
    name: "Siegfried_of_Denesle",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Melee,
    strength: 5,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Sile_de_Tansarville: {
    name: "Sile_de_Tansarville",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Range,
    strength: 5,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Trebuchet: {
    name: "Trebuchet",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Siege,
    strength: 6,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Ves: {
    name: "Ves",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Melee,
    strength: 5,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
  Yarpen_Zigrin: {
    name: "Yarpen_Zigrin",
    fraction: Fraction.NorthernRealms,
    type: CardType.Unit,
    row: CardRow.Melee,
    strength: 2,
    ability: CardAbilities.None,
    comment: "Part of a base deck",
  },
};

export const baseDeck = [
  cards["Ballista"],
  cards["Ballista"],
  cards["Dethmold"],
  cards["Dun_Banner_Medic"],
  cards["Dun_Banner_Medic"],
  cards["Kaedweni_Siege_Expert"],
  cards["Kaedweni_Siege_Expert"],
  cards["Keira_Metz"],
  cards["Prince_Stennis"],
  cards["Redanian_Foot_Soldier"],
  cards["Redanian_Foot_Soldier"],
  cards["Sabrina_Glevissig"],
  cards["Sheldon_Skaggs"],
  cards["Siegfried_of_Denesle"],
  cards["Sile_de_Tansarville"],
  cards["Trebuchet"],
  cards["Trebuchet"],
  cards["Ves"],
  cards["Yarpen_Zigrin"],
];

export const defaultState: IGameState = {
  gameMode: GameMode.Single,
  gameOver: false,
  message: "",
  activePlayer: "player1",
  player1: {
    name: "Norvil",
    fraction: Fraction.NorthernRealms,
    deck: baseDeck,
    discard: [],
    hand: [],
    totalScore: 0,
    battlefield: {
      melee: [],
      range: [],
      siege: [],
    },
  },
  player2: {
    name: "Opponent",
    fraction: Fraction.NorthernRealms,
    deck: baseDeck,
    discard: [],
    hand: [],
    totalScore: 0,
    battlefield: {
      melee: [],
      range: [],
      siege: [],
    },
  },
};
